export const INTROSLIDE = {
  VIEWED: "INTROSLIDE_VIEWED",
};
export const FAVORITE = {
  ADD_POKE: "POKE_FAVORITE_ADD",
  REMOVE_POKE: "POKE_FAVORITE_REMOVE",
};

export const STATUS = {
  CATCH_POKE: "POKE_STATUS_CATCH",
  RELEASE_POKE: "POKE_STATUS_RELEASE",
};
